<?php
// module/Album/view/album/album/index.phtml:

$title = 'Historial';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
<tr>
    <th>Customer Name</th>
    <th>Customer Email</th>
    <th>Customer Mobile</th>
    <th>Status</th>
    <th>Created At</th>
    <th>Updated At</th>
</tr>
<?php foreach ($orders as $order) : ?>
    <tr>
        <td><?= $this->escapeHtml($order['customer_name']) ?></td>
        <td><?= $this->escapeHtml($order['customer_email']) ?></td>
        <td><?= $this->escapeHtml($order['customer_mobile']) ?></td>
        <td><?= $this->escapeHtml($order['status']) ?></td>
        <td><?= $this->escapeHtml($order['created_at']) ?></td>
        <td><?= $this->escapeHtml($order['updated_at']) ?></td>
    </tr>
<?php endforeach; ?>
</table>